export const STATUSES = {
  EVALUATE: 'evaluate',
  APPLIED: 'applied',
  RECRUITER: 'recruiter',
  INTERVIEW: 'interview',
  OFFER: 'offer',
  REJECTED: 'rejected',
  PASSED: 'passed',
};

export const STATUS_META = {
  evaluate:  { label: 'To evaluate', color: '#888780', bg: '#F1EFE8', border: '#B4B2A9' },
  applied:   { label: 'Applied',     color: '#185FA5', bg: '#E6F1FB', border: '#85B7EB' },
  recruiter: { label: 'Recruiter',   color: '#3B6D11', bg: '#EAF3DE', border: '#97C459' },
  interview: { label: 'Interview',   color: '#27500A', bg: '#C0DD97', border: '#639922' },
  offer:     { label: 'Offer',       color: '#085041', bg: '#9FE1CB', border: '#1D9E75' },
  rejected:  { label: 'Rejected',    color: '#791F1F', bg: '#FCEBEB', border: '#F09595' },
  passed:    { label: 'Passed',      color: '#5F5E5A', bg: '#F1EFE8', border: '#D3D1C7' },
};

export const SOURCES = ['Ashby', 'Greenhouse', 'LinkedIn', 'Workday', 'Direct', 'Referral', 'Staffing', 'Other'];

export const sampleJobs = [
  {
    id: '1',
    role: 'Senior PM, AI Automation',
    company: 'MeridianLink',
    status: STATUSES.RECRUITER,
    dateApplied: '2026-06-17',
    salary: '$150–180K',
    source: 'Ashby',
    network: '',
    followUpDate: '2026-06-29',
    notes: 'Recruiter interview Mon 6/22. Strong fit on lending + AI angle.',
    gmailUpdate: null,
  },
  {
    id: '2',
    role: 'Data PM, Financial Crime',
    company: 'LexisNexis',
    status: STATUSES.RECRUITER,
    dateApplied: '2026-06-18',
    salary: 'Not listed',
    source: 'Direct',
    network: 'BHSG contact',
    followUpDate: '2026-06-30',
    notes: 'Came via BHSG email. FCC angle is a strong match.',
    gmailUpdate: 'Interview invite received — check inbox.',
  },
  {
    id: '3',
    role: 'Sr PM, Fraud & Trust',
    company: 'Instacart',
    status: STATUSES.APPLIED,
    dateApplied: '2026-06-18',
    salary: 'Not listed',
    source: 'Greenhouse',
    network: '',
    followUpDate: '2026-06-25',
    notes: 'Real-time ML decision platform angle. Perfect domain fit.',
    gmailUpdate: null,
  },
  {
    id: '4',
    role: 'Sr PM, Trust & Safety',
    company: 'DoorDash',
    status: STATUSES.APPLIED,
    dateApplied: '2026-06-22',
    salary: 'Not listed',
    source: 'Greenhouse',
    network: '',
    followUpDate: '2026-07-06',
    notes: '',
    gmailUpdate: null,
  },
  {
    id: '5',
    role: 'Sr PM, Fraud & Trust',
    company: 'ZoomInfo',
    status: STATUSES.APPLIED,
    dateApplied: '2026-06-16',
    salary: 'Not listed',
    source: 'Ashby',
    network: '',
    followUpDate: '2026-06-30',
    notes: 'Identity resolution focus. Good stretch role.',
    gmailUpdate: null,
  },
  {
    id: '6',
    role: 'New Leader – Pitch Us',
    company: 'SentiLink',
    status: STATUSES.EVALUATE,
    dateApplied: null,
    salary: 'Not listed',
    source: 'Direct',
    network: '',
    followUpDate: null,
    notes: 'Open-ended pitch track. Needs a product proposal. High upside.',
    gmailUpdate: null,
  },
  {
    id: '7',
    role: 'Fraud Solutions PM – Sr Director',
    company: 'FICO',
    status: STATUSES.APPLIED,
    dateApplied: '2026-06-09',
    salary: '$164–258K',
    source: 'Direct',
    network: '',
    followUpDate: '2026-06-23',
    notes: 'Technical bridge role. EFS / Falcon fraud solution experience relevant.',
    gmailUpdate: null,
  },
  {
    id: '8',
    role: 'Lead PM, Payments & Trust',
    company: 'Lime',
    status: STATUSES.REJECTED,
    dateApplied: '2026-06-10',
    salary: 'Not listed',
    source: 'Greenhouse',
    network: '',
    followUpDate: null,
    notes: 'Rejection 6/18.',
    gmailUpdate: null,
  },
  {
    id: '9',
    role: 'Principal PM, Identity Fraud',
    company: 'Yahoo',
    status: STATUSES.REJECTED,
    dateApplied: '2026-05-08',
    salary: 'Not listed',
    source: 'Direct',
    network: '',
    followUpDate: null,
    notes: 'Strong interview. Product audit of Yahoo auth flows landed well.',
    gmailUpdate: null,
  },
  {
    id: '10',
    role: 'Senior PM, Fraud & Trust',
    company: 'DoorDash',
    status: STATUSES.INTERVIEW,
    dateApplied: '2026-06-22',
    salary: 'Not listed',
    source: 'Greenhouse',
    network: '',
    followUpDate: '2026-06-28',
    notes: 'Panel round pending.',
    gmailUpdate: null,
  },
];
